### ISSUE TITLE
Tasks alignment in Grid issue

### ISSUE THREAD

**Issue by mahmad2504** [jsGanttImproved/jsgantt-improved#43]
Tasks are not aligned correctly in grid as per start and end date and if the project is of larger duration this becomes significantly noticeable , making it virtually useless for serious project. This is a blocker and it would be great if resolved early. In image one can see that task is almost offset by a week

https://user-images.githubusercontent.com/15646324/28788779-d048ded6-763b-11e7-9e4d-04643777bcc0.png)

**Comment by RickCardoso** [comment]
@mahmad2504 , this bug is fixed in the pending pull request #41 which addresses issue #36 . I'll close this issue for now and we'll reopen if necessary. We'll merge the pull request ASAP

**Comment by mahmad2504** [comment]
It fixes it partially. As the projects spreads across 5-6 months , the tasks still loose their alignment gradually and becomes significant for tasks 5-6 months in future.  I had also partially fixed it by increasing pColWidth by 1.8 but it was through trial and error not a well thought fix. 

SGantt.getOffset=function(pStartDate, pEndDate, pColWidth, pFormat)
......
........
	var vTaskRight=(tmpTaskEnd-tmpTaskStart)/3600000; // Length of task in hours
        pColWidth = pColWidth + 1.8;
